# action.yml
name: 'Smart Scan'
description: 'This action decides whether or not to run a CodeQL scan in your PR'
inputs:
  openai_api_key: 
    description: 'OpenAI API Key'
    required: true
    default: 'things'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    # OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    DIFF_URL: ${{ github }}
    # DIFF_URL: 'hello'
