# action.yml
name: 'Smart Scan'
description: 'This action decides whether or not to run a CodeQL scan in your PR'
inputs:
  gh_token: 
    description: 'github token'
    required: true
  model: 
    description: 'Model name.  Defaults to gpt-3.5-turbo'
    required: true
    default: 'gpt-3.5-turbo'
  openai_api_key: 
    description: 'OpenAI API Key'
    required: true
    default: 'oaikey'
  azure_api_key: 
    description: 'Azure OpenAI Service API Key'
    required: true
    default: 'azure_key'
  azure_endpoint: 
    description: 'Azure OpenAI Service Endpoint'
    required: true
    default: 'asure_endpotint'
  azure_deployment_id: 
    description: 'Azure OpenAI Service Deployment ID'
    required: true
    default: null
outputs:
  decision:
    description: 'decision on whether or not to run CodeQL'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{ inputs.gh_token }}
   - ${{ inputs.model }}
   - ${{ inputs.openai_api_key }}
   - ${{ inputs.azure_api_key }}
   - ${{ inputs.azure_endpoint }}
   - ${{ inputs.azure_deployment_id }}

