# action.yml
name: 'Smart Scan'
description: 'This action decides whether or not to run a CodeQL scan in your PR'
inputs:
  openai_api_key: 
    description: 'OpenAI API Key'
    required: true
  gh_token: 
    description: 'github token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{ inputs.openai_api_key }}
   - ${{ inputs.gh_token }}

