# action.yml
name: 'Smart Scan'
description: 'This action decides whether or not to run a CodeQL scan in your PR'
inputs:
  openai_api_key: 
    description: 'OpenAI API Key'
    required: true
    default: 'things'
  diff_url:
    description: 'URL of the diff'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{ inputs.openai_api_key }}
   - ${{ inputs.diff_url }}

