name: "Smart Scan - Test"
on: push
jobs:
  smart-scan:
    name: "testing"
    runs-on: ubuntu-latest

    steps:
      - uses: leftrightleft/smart-scan@main 
        with:
          openai_api_key: ${{ secrets.OPENAI_KEY }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          
    
